export const addonsList = {
  Data: [
    {
        uuid: "6b5736ce-ec3a-4b29-9070-8ad9ca674aa0",
        type: "FOOD",
        title: "Paneer Tikka Sandwich (Plain)",
        subtitle: "Delivered at boarding point",
        description: "Soft chunks of paneer marinated in tikka masala spices stuffed between bread slices",
        images: [
          {
            altText: "Paneer Tikka Sandwich",
            heading1: "",
            heading2: "",
            isActive: true,
            priority: 1,
            url: "/Paneer-Tikka-Sandwich-_300x94px.png",
          },
        ],
        tags: null,
        isFreehold: false,
        date: "2020-05-22",
        expiryDate: "",
        priority: 4,
        minUnit: 2,
        maxUnit: 6,
        cityID: 122,
        cityName: "Bengaluru",
        mrp: 72,
        displayPrice: 69,
        tnc: [
          "redBus shall neither be liable nor responsible for any actions or inactions of service providers nor any breach of conditions",
          "representations or warranties by the suppliers or service provider and hereby expressly disclaim and any all responsibility and liability in that regard",
          "redBus further expressly disclaims any warranties or representations (express or implied) in respect of quality",
          "suitability",
          "accuracy",
          "reliability",
          "completeness",
          "timeliness",
          "performance",
          "safety",
          "or legality of the services listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the website",
          "Voucher is valid only for the food to be delivered for a given date",
          "time and the delivery location",
          "Price is inclusive of all taxes",
          "Delivery partner details will be shared to you via SMS 30 mins before your bus departure time. You can coordinate with the person for the food order delivery",
          "Delivery partner details will be shared to you via SMS 30 mins before your bus departure time. You can coordinate with the person for the food order delivery",
          "If the vendor cancels the order or is not able to deliver the food at predefined time",
          "you will be eligible for a refund. Amount collected from you will be refunded by redBus within 5-7 business working days",
        ],
        thingsToCarry: [
          "Booking confirmation voucher on mobile or a physical copy",
        ],
        inclusions: [
          "Food as per menu",
          "Basic cutlery along with food package wherever applicable",
        ],
        exclusions: [
          "Anything not mentioned as a part of this additional service",
        ],
        howToRedeem: [
          "Delivery partner details will be shared to you via SMS 30 mins before your bus departure time. Please be present at the departure point 15 minutes before the bus departure time and coordinate with the delivery person for the food order delivery",
          "if required",
          "Show the booking confirmation voucher to the delivery partner and collect your food order",
        ],
        starRating: 0,
        cancellationPolicy: "0:2:100:0;2:-1:0:0",
        extra: {
          familyID: 961,
        },
        configuredFor: "BOARDING",
        created: "2020-03-17T08:40:07Z",
        updated: "2020-03-17T08:40:07Z",
        vendorType: "PETOO",
        MrpInFloat: 72.449997,
        displayPriceInFloat: 69,
        cancellationPolicyArray: [
          {
            chargesValue: "Fully refundable",
            description: "Before 21st May 10:00 PM",
          },
          {
            chargesValue: "100%",
            description: "After 21st May 10:00 PM & Before 22nd May 12:00 AM",
          },
        ],
        cta: null,
        optIn: false,
        unitType: "bike",
        showAsCard: false,
      },
      {
        uuid: "2c71eeba-99ee-467a-a0ae-80883778a4c2",
        type: "FOOD",
        title: "Corn & Cheese Sandwich (Plain)",
        subtitle: "Delivered at boarding point\t",
        description: "The combination of sweet corn along with cream cheese and other spices provides a sweet and savoury taste for this all day snacker",
        images: [
          {
            altText: "test",
            heading1: "",
            heading2: "",
            isActive: true,
            priority: 0,
            url: "/Corn--Cheese-sandwhich_300x94px.png",
          },
        ],
        tags: null,
        isFreehold: false,
        date: "2020-05-22",
        expiryDate: "2020-08-08",
        priority: 1,
        minUnit: 1,
        maxUnit: 6,
        cityID: 122,
        cityName: "Bengaluru",
        mrp: 71,
        displayPrice: 69,
        tnc: [
          "redBus shall neither be liable nor responsible for any actions or inactions of service providers nor any breach of conditions",
          " representations or warranties by the suppliers or service provider and hereby expressly disclaim and any all responsibility and liability in that regard",
          "redBus further expressly disclaims any warranties or representations (express or implied) in respect of quality",
          " suitability",
          " accuracy",
          " reliability",
          " completeness",
          " timeliness",
          " performance",
          " safety",
          " or legality of the services listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the website",
          "Voucher is valid only for the food to be delivered for a given date ",
          " time and the delivery location",
          "Price is inclusive of all taxes",
          "Delivery partner details will be shared to you via SMS 30 mins before your bus departure time. You can coordinate with the person for the food order delivery",
          "Delivery partner details will be shared to you via SMS 30 mins before your bus departure time. You can coordinate with the person for the food order delivery",
          "If the vendor cancels the order or is not able to deliver the food at predefined time",
          " you will be eligible for a refund. Amount collected from you will be refunded by redBus within 5-7 business working days",
        ],
        thingsToCarry: [
          "Booking confirmation voucher on mobile or a physical copy",
        ],
        inclusions: [
          "Food as per menu",
          "Basic cutlery along with food package wherever applicable",
        ],
        exclusions: [
          "Anything not mentioned as a part of this additional service",
        ],
        howToRedeem: [
          "Delivery partner details will be shared to you via SMS 30 mins before your bus departure time. Please be present at the departure point 15 minutes before the bus departure time and coordinate with the delivery person for the food order delivery",
          " if required",
          "Show the booking confirmation voucher to the delivery partner and collect your food order",
        ],
        starRating: 0,
        cancellationPolicy: "0:2:100:0;2:-1:0:0",
        extra: {
          familyID: 1102,
        },
        configuredFor: "BOARDING",
        created: "2020-02-03T06:58:30Z",
        updated: "2020-02-24T09:54:38Z",
        vendorType: "PETOO",
        MrpInFloat: 71.449997,
        displayPriceInFloat: 69,
        cancellationPolicyArray: [
          {
            chargesValue: "Fully refundable",
            description: "Before 21st May 10:00 PM",
          },
          {
            chargesValue: "100%",
            description: "After 21st May 10:00 PM & Before 22nd May 12:00 AM",
          },
        ],
        cta: null,
        optIn: false,
        unitType: "",
        showAsCard: false,
      },
      {
        uuid: "f911492c-5399-4353-bce1-16f9681e6869",
        type: "FOOD",
        title: "Chicken & Mayo Sandwich (Plain)",
        subtitle: "Delivered at boarding point\t",
        description: "Shredded boiled chicken mixed with mayonnaise and stuffed between bread slices. Delectable option for any time of the day",
        images: [
          {
            altText: "Chicken &Mayo Sandwich (Plain)",
            heading1: "",
            heading2: "",
            isActive: true,
            priority: 0,
            url: "/Chicken--Mayo-sandwich_300x94px.png",
          },
        ],
        tags: null,
        isFreehold: false,
        date: "2020-05-22",
        expiryDate: "2020-08-08",
        priority: 1,
        minUnit: 1,
        maxUnit: 6,
        cityID: 122,
        cityName: "Bengaluru",
        mrp: 83,
        displayPrice: 79,
        tnc: [
          "redBus shall neither be liable nor responsible for any actions or inactions of service providers nor any breach of conditions, representations or warranties by the suppliers or service provider and hereby expressly disclaim and any all responsibility and liability in that regard",
          "redBus further expressly disclaims any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, or legality of the services listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the website",
          "Voucher is valid only for the food to be delivered for a given date , time and the delivery location",
          "Price is inclusive of all taxes",
          "Delivery partner details will be shared to you via SMS 30 mins before your bus departure time. You can coordinate with the person for the food order delivery",
          "If the vendor cancels the order or is not able to deliver the food at predefined time, you will be eligible for a refund. Amount collected from you will be refunded by redBus within 5-7 business working days",
        ],
        thingsToCarry: [
          "Booking confirmation voucher on mobile or a physical copy",
        ],
        inclusions: [
          "Food as per menu",
          "Basic cutlery along with food package wherever applicable",
        ],
        exclusions: [
          "Anything not mentioned as a part of this additional service",
        ],
        howToRedeem: [
          "Delivery partner details will be shared to you via SMS 30 mins before your bus departure time. Please be present at the departure point 15 minutes before the bus departure time and coordinate with the delivery person for the food order delivery, if required",
          "Show the booking confirmation voucher to the delivery partner and collect your food order",
        ],
        starRating: 0,
        cancellationPolicy: "0:2:100:0;2:-1:0:0",
        extra: {
          familyID: 1103,
        },
        configuredFor: "BOARDING",
        created: "2020-02-25T06:19:52.187755Z",
        updated: "2020-02-25T06:19:52.187755Z",
        vendorType: "PETOO",
        MrpInFloat: 82.949997,
        displayPriceInFloat: 79,
        cancellationPolicyArray: [
          {
            chargesValue: "Fully refundable",
            description: "Before 21st May 10:00 PM",
          },
          {
            chargesValue: "100%",
            description: "After 21st May 10:00 PM & Before 22nd May 12:00 AM",
          },
        ],
        cta: null,
        optIn: false,
        unitType: "",
        showAsCard: false,
      },
      {
        uuid: "5731df1b-d0d9-4cb0-b90d-e2eedfa228cf",
        type: "ACTIVITY",
        title: "Bike Rentals in Calangute Goa (Activa)",
        subtitle: "Bike Rentals in Calangute (Activa)",
        description: "Bike rentals in Goa are extremely popular and in demand always. Roam around the city on your bike and explore the sandy beaches, quaint charming streets and scenic beauty.",
        images: [
          {
            altText: "Bike Rentals in Calangute Goa (Activa)",
            heading1: "",
            heading2: "",
            isActive: true,
            priority: 0,
            url: "/testAuto.jpg",
          },
        ],
        tags: null,
        isFreehold: false,
        date: "2020-05-28",
        expiryDate: "2020-05-28",
        priority: 0,
        minUnit: 2,
        maxUnit: 30,
        cityID: 210,
        cityName: "Goa",
        mrp: 399,
        displayPrice: 399,
        tnc: [
          "Bike will be booked for your date of arrival in Goa.",
          "Any issues with the Bike needs to be highlighted at the time of delivery, no request would be entertained after delivery of the  Bike",
          "Rs 500 Refundable deposit needs to be paid to the vendor at the time of delivery of the bike.",
          "redBus shall neither be liable nor responsible for any actions or inactions of service providers nor any breach of conditions, representations or warranties by the suppliers or service provider and hereby expressly disclaim and any all responsibility and liability in that regard",
          "redBus further expressly disclaims any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, or legality of the services listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the website",
        ],
        thingsToCarry: [],
        inclusions: [
          "Activa Bike\r\n",
          "Bike would be handed over at the hotel in the Calangute beach area only.\r\n",
          "Drop location would be informed by the vendor\r\n",
          "All prices are inclusive of taxes and service charge",
        ],
        exclusions: [
          "Tips and gratuities (Optional)",
        ],
        howToRedeem: [
          "After purchasing the voucher customer shall get an e-voucher via WhatsApp/mail/under MY TRIP section on the app. Operator details shall be mentioned on the voucher.\r\n",
          "Call the operator to confirm the reservation.\r\n",
          "On the day of activity, operator shall deliver the vehicle at the hotel in the area mentioned in the app.\r\n",
          "Operator would check the voucher and redeem the same before handing over the bike.\r\n",
        ],
        starRating: 4.8,
        cancellationPolicy: "24:-1:0:0",
        extra: {
          activityID: 62972,
          cityName: "Goa",
          date: "2020-05-28",
          hasSlot: false,
          instantConfirmation: true,
          isAutoredeem: false,
          productCategoryTag: "279",
          rateInventories: [
            {
              availableCount: 999999,
              cancellationPolicy: [
                {
                  chargesValue: "Fully refundable",
                  description: "Before 27th May 11:59 PM",
                },
              ],
              childPrice: 0,
              date: "2020-05-28",
              duration: 0,
              endTime: "",
              expiryDate: "28-May-2020",
              expiryText: "",
              infantPrice: 0,
              isCutOffPassed: false,
              maxUnits: 30,
              minimumUnits: 2,
              rateInventoryID: 4287012860,
              seniorPrice: 0,
              startTime: "",
              unitPrice: 399,
            },
          ],
          ratePlanID: 197624,
          ratePlanName: "Bike Rentals in Calangute (Activa) For 2 Days",
          unitType: 1,
          vendorCityID: 15,
          venueDetail: {
            address: "1/234A, Gauravaddo, Calangute",
            contact: "7011398168",
            location: {
              lat: 15.537211,
              lon: 73.752563,
            },
          },
        },
        configuredFor: "DROPPING",
        created: "2019-12-02T06:07:01Z",
        updated: "2019-12-02T06:07:01Z",
        vendorType: "ACME",
        MrpInFloat: 399,
        displayPriceInFloat: 399,
        cancellationPolicyArray: [
          {
            chargesValue: "Fully refundable",
            description: "Before 27th May 11:59 PM",
          },
        ],
        cta: null,
        optIn: false,
        unitType: "",
        showAsCard: false,
      },
      {
        uuid: "5731df1b-d0d9-4cb0-b90d-e2eedfa228cg",
        type: "ACTIVITY",
        title: "Bike Rentals in Calangute Goa (Activa)",
        subtitle: "Bike Rentals in Calangute (Activa)",
        description: "Bike rentals in Goa are extremely popular and in demand always. Roam around the city on your bike and explore the sandy beaches, quaint charming streets and scenic beauty.",
        images: [
          {
            altText: "Bike Rentals in Calangute Goa (Activa)",
            heading1: "",
            heading2: "",
            isActive: true,
            priority: 0,
            url: "/testAuto.jpg",
          },
        ],
        tags: null,
        isFreehold: false,
        date: "2020-05-28",
        expiryDate: "2020-05-28",
        priority: 0,
        minUnit: 2,
        maxUnit: 30,
        cityID: 210,
        cityName: "Goa",
        mrp: 399,
        displayPrice: 399,
        tnc: [
          "Bike will be booked for your date of arrival in Goa.",
          "Any issues with the Bike needs to be highlighted at the time of delivery, no request would be entertained after delivery of the  Bike",
          "Rs 500 Refundable deposit needs to be paid to the vendor at the time of delivery of the bike.",
          "redBus shall neither be liable nor responsible for any actions or inactions of service providers nor any breach of conditions, representations or warranties by the suppliers or service provider and hereby expressly disclaim and any all responsibility and liability in that regard",
          "redBus further expressly disclaims any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, or legality of the services listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the website",
        ],
        thingsToCarry: [],
        inclusions: [
          "Activa Bike\r\n",
          "Bike would be handed over at the hotel in the Calangute beach area only.\r\n",
          "Drop location would be informed by the vendor\r\n",
          "All prices are inclusive of taxes and service charge",
        ],
        exclusions: [
          "Tips and gratuities (Optional)",
        ],
        howToRedeem: [
          "After purchasing the voucher customer shall get an e-voucher via WhatsApp/mail/under MY TRIP section on the app. Operator details shall be mentioned on the voucher.\r\n",
          "Call the operator to confirm the reservation.\r\n",
          "On the day of activity, operator shall deliver the vehicle at the hotel in the area mentioned in the app.\r\n",
          "Operator would check the voucher and redeem the same before handing over the bike.\r\n",
        ],
        starRating: 4.8,
        cancellationPolicy: "24:-1:0:0",
        extra: {
          activityID: 62972,
          cityName: "Goa",
          date: "2020-05-28",
          hasSlot: false,
          instantConfirmation: true,
          isAutoredeem: false,
          productCategoryTag: "279",
          rateInventories: [
            {
              availableCount: 999999,
              cancellationPolicy: [
                {
                  chargesValue: "Fully refundable",
                  description: "Before 27th May 11:59 PM",
                },
              ],
              childPrice: 0,
              date: "2020-05-28",
              duration: 0,
              endTime: "",
              expiryDate: "28-May-2020",
              expiryText: "",
              infantPrice: 0,
              isCutOffPassed: false,
              maxUnits: 30,
              minimumUnits: 2,
              rateInventoryID: 4287012860,
              seniorPrice: 0,
              startTime: "",
              unitPrice: 399,
            },
          ],
          ratePlanID: 197624,
          ratePlanName: "Bike Rentals in Calangute (Activa) For 2 Days",
          unitType: 1,
          vendorCityID: 15,
          venueDetail: {
            address: "1/234A, Gauravaddo, Calangute",
            contact: "7011398168",
            location: {
              lat: 15.537211,
              lon: 73.752563,
            },
          },
        },
        configuredFor: "DROPPING",
        created: "2019-12-02T06:07:01Z",
        updated: "2019-12-02T06:07:01Z",
        vendorType: "ACME",
        MrpInFloat: 399,
        displayPriceInFloat: 399,
        cancellationPolicyArray: [
          {
            chargesValue: "Fully refundable",
            description: "Before 27th May 11:59 PM",
          },
        ],
        cta: null,
        optIn: false,
        unitType: "",
        showAsCard: false,
      },
    ],
  };
